### ISSUE TITLE
Cleaning unit motion parts ordered/designed 

### ISSUE THREAD

**Issue by TrevorDecker** [TrevorDecker/CMU_Mechatronics_2015_TeamB#25]
Select the power chain/track and motor we want to use

**Comment by TrevorDecker** [comment]
@ihartwig  did you order the steppers?

**Comment by ihartwig** [comment]
Not yet. We need to submit them through the process for going over budget,
but I haven't looked into that yet.

Ian Hartwig [spacepenguine@gmail.com]

**Comment by TrevorDecker** [comment]
Done
