### ISSUE TITLE
Develop Gripper 

### ISSUE THREAD

**Issue by TrevorDecker** [TrevorDecker/CMU_Mechatronics_2015_TeamB#5]
Design the Gripper

**Comment by stephaniechen456** [comment]
Origin: Weight
Description: Not enough area on 80/20 to grip for weight from robot and gearbox. Dynamic load from pivoting also needs to be considered

**Comment by stephaniechen456** [comment]
Origin: Coupler not properly attached to motor shaft or threaded rod
Description: Motor shaft and bolt slip in the coupler, leading to no actuation

**Comment by TrevorDecker** [comment]
Prototype 2 has been built, can currently hold about 5lb's 
plan to optimize between now and march 22nd If it can not hold 20ish lb we will move to a different redesign based heavily on a clamp.

**Comment by ihartwig** [comment]
I think we really need to use the (immense) weight of our own robot to hold ourself up. A good example of this comes from the 2010 FIRST Robotics Challenge where the 120-150 lb robots had to lift themselves off the ground. [Many of the successful teams](http://www.adambots.com/wp-content/gallery/first/2010/robot/F10-Robot-01.jpg) just touched the pole on opposite sides at 2 points and used gravity to keep them at a fixed point on the pole. We can do the same by using oversized c-channel as our grippers, applying the rubber c channel on the edges as grip, and using the pivot gearbox to rotate the c channel into a binding position.

**Comment by TrevorDecker** [comment]
Decided to use a piece of C channel that we found
