### ISSUE TITLE
Asseble  Extending Arm

### ISSUE THREAD

**Issue by stephaniechen456** [TrevorDecker/CMU_Mechatronics_2015_TeamB#6]

**Comment by stephaniechen456** [comment]
Origin: Width of arm and cleaning unit
Description: The width of the extending arm provides a moment that causes the robot to want to tip away from the window

**Comment by stephaniechen456** [comment]
Origin: Joints
Description: There might be play in the bearing and bracket attachment on the two beams. This will cause torque at the joints and may affect our performance in moving linearly.

**Comment by stephaniechen456** [comment]
Origin: Weight
Description: Mechanisms (motors, cleaning unit, drive shafts) weigh down extending arm, creating bending in undesirable places.

**Comment by TrevorDecker** [comment]
Cad model finished need to machine parts and assemble system

**Comment by TrevorDecker** [comment]
Fully assembled, and operational.  Still need to add some convince holes to allow for smother operation, and easier maintenance.
